apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: echo-rollout
spec:
  replicas: 4
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: echo

  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
        - "-text=VERSION 7"
        ports:
        - containerPort: 5678

  strategy:
    # blueGreen:
    #   activeService: echo-active
    #   previewService: echo-preview
    #   autoPromotionEnabled: false
    canary:
      stableService: echo-stable 
      canaryService: echo-canary
      steps:
      - setWeight: 25
      - pause:
          duration: 30s

      - setWeight: 50
      - pause:
          duration: 30s

      - setWeight: 100
